include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - one_member_abstracts
    - only_throw_errors
    - package_api_docs
    - prefer_final_in_for_each
    - camel_case_types
    - library_names
    - always_use_package_imports
    #- avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_empty_else
    - unnecessary_brace_in_string_interps
    - avoid_redundant_argument_values
    - leading_newlines_in_multiline_strings
    # formatting
    #- lines_longer_than_80_chars
    - curly_braces_in_flow_control_structures
    # doc comments
    - slash_for_doc_comments
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_web_libraries_in_flutter
    - always_put_control_body_on_new_line
    - control_flow_in_finally
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks
    - unsafe_html
    - use_build_context_synchronously
    - use_key_in_widget_constructors
    #style
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_double_and_int_checks
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_multiple_declarations_per_line
    - avoid_shadowing_type_parameters
    - avoid_types_on_closure_parameters
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - constant_identifier_names
    - empty_catches
    - empty_constructor_bodies
    - eol_at_end_of_file
    - exhaustive_cases
    - file_names
    - flutter_style_todos
    - library_prefixes
    - no_default_cases
    - noop_primitive_operations
    - null_closures
    - prefer_final_fields
    - prefer_final_locals
